### ISSUE TITLE
Weak linking of KextManagerUnloadKextByIdentifier doesn't work on OS X 10.6

### ISSUE THREAD

**Issue by maltoe** [osxfuse/support#1]
Hi,

using the latest osxfuse (osxfuse/osxfuse@69ae49f345457facd74a70439d8fa31a8e4dac19) and Xcode 4.2 on Mac OS X 10.6.8 leads to 

```
dyld: Symbol not found: _KextManagerUnloadKextWithIdentifier
  Referenced from: /Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse
  Expected in: flat namespace
 in /Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse
```

Seems the `__attribute__((weak_import))` on that call isn't working or some linker flags are wrong.

 Would be glad to provide additional information, yet I'm not really an expert on linker errors on OSX, so can not fix it myself.

Best regards,
Malte

**Comment by bfleischer** [comment]
Hi Malte,

the version of osxfuse you built (master branch) contains some experimental changes and is not the currently stable version (osxfuse-2 branch). The osxfuse-2 branch should compile fine on Mac OS X 10.6 with Xcode 4.2. 

I'm afraid but the dyld error you are seeing is caused by a bug in Apple's linker. The master branch version of load_osxfuse is designed to support KextLoader API functions (if available) that have been introduced in Mac OS X 10.6 and 10.7, while being built with the Mac OS X 10.5 SDK (or 10.6 in your case). The function KextManagerUnloadKextWithIdentifier (the one that is missing) was introduced in OS X 10.7 and is therefore not available on your system. `__attribute__((weak_import))` should take care of this. This works fine for Xcode 3.2 and Xcode >= 4.5. But for everything in between the linker does not mark the symbol a weak and that's why you are getting the "Symbol not found" error. There does not seems to be an easy workaround. If you are interested in the details see ["Fun with weak dynamic linking"](http://glandium.org/blog/?p=2764).

I recommend building the stable osxfuse-2 branch or, in case you want to play with the master branch, built osxfuse using Xcode 3.2.6. The official release version of osxfuse is built using Xcode 3.2.6 (and Xcode 5.0.1 for OS X 10.9).

**Comment by maltoe** [comment]
Hi Benjamin,

thanks for your detailed explanation.

I'm aware of the fact that the master branch isn't stable yet. However, I was playing around with different versions of osxfuse and a particular fuse file system on various versions of OSX. I was specifically interested in getting your VNOP_ALLOCATE (osxfuse/kext@5e40d9faacf661f28bffc84661ce44dcea1e2753) implementation, so I thought I should give it a try. Apart from the weak linking problem, the master branch seems to work fine, though. For our purposes, simply disabling the weak linked KextManager import and relying on external kextunload is fine.

When are you planning to release the master branch into the wild? Do you have some kind of roadmap?

Thanks again,
malte

**Comment by bfleischer** [comment]
> When are you planning to release the master branch into the wild?

Yesterday. osxfuse 3.2.0 can be found here: https://github.com/osxfuse/osxfuse/releases
